name: schedule_fit
description: "ScheduleFit"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #splash screen e icon
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

  #i16n/l10n
  flutter_localization: ^0.2.0
  intl: any
  country_flags: ^2.2.0

  #ui customization
  cupertino_icons: ^1.0.6
  stroke_text: ^0.0.3
  auto_size_text_field: ^2.2.4
  table_calendar: ^3.1.3

  #utils
  path: any
  flutter_gen: any
  url_launcher: ^6.2.6
  provider: ^6.1.2

  #database
  sqflite: ^2.3.3+1
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  drift_dev: ^2.21.2
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  generate:
    - gen_l10n

  assets:
    - assets/images/
    - assets/muscles/

  fonts:
    - family: Cooper Hewitt
      fonts:
        - asset: assets/fonts/cooper-hewitt.heavy-italic.otf
          style: italic
