enum AppColors {
  primaryColor,
  secondaryColor,
  pageBackgroundColor,
  slidingPanelColor,
  calendarSelectedDayColor,
  calendarDaysOfWeekColor,
  calendarDaysOfWeekendColor,
  noExercisesColor,
  accordionTextHeaderColor,
  accordionBackgroundColor,
  exerciseCardColor,
  exerciseCardTextColor,
  dropdownButtonTextColor,
  dropdownDaysOfWeekColor,
  cancelColor,
  checkColor,
  crossColor
}
